name       : zlib
version    : 1.2.12
release    : 22
source     :
    - https://github.com/madler/zlib/archive/refs/tags/v1.2.12.tar.gz : d8688496ea40fb61787500e863cc63c9afcbc524468cedeb478068924eb54932
homepage   : http://www.zlib.net
license    : ZLIB
component  :
    - system.base
    - minizip : system.utils
    - minizip-devel : programming.devel
summary    :
    - zlib (Compression library)
    - minizip : Mini zip and unzip based on zlib
    - minizip-devel : Development files for zlib-minizip
description:
    - The zlib library is a compression library that aims to be unobtrusive.
    - minizip : Mini zip and unzip based on zlib
    - minizip-devel : Mini zip and unzip based on zlib
devel      : yes
emul32     : yes
patterns   :
    - minizip :
        - /usr/lib64/libminizip.so.*
    - minizip-devel :
        - /usr/include/minizip/*
        - /usr/lib64/libminizip.a
        - /usr/lib64/libminizip.so
        - /usr/lib64/pkgconfig/minizip.pc
setup      : |
    %patch -p1 < $pkgfiles/no_ldconfig.patch
    %patch -p1 < $pkgfiles/fix-cc-configure-issue.patch

    ./configure --prefix=/usr --libdir=%libdir%

    # configure minizip
    pushd contrib/minizip
    if [[ -z "${EMUL32BUILD}" ]]; then
        %reconfigure
    fi
    popd
build      : |
    %make

    # build minizip
    pushd contrib/minizip
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make
    fi
    popd
install    : |
    %make_install

    # install minizip
    pushd contrib/minizip
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make_install
    fi
    popd
