name       : zlib
version    : 1.2.11
release    : 19
source     :
    - http://zlib.net/zlib-1.2.11.tar.gz : c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
homepage   : http://www.zlib.net
license    : ZLIB
component  :
    - system.base
    - minizip : system.utils
    - minizip-devel : programming.devel
summary    :
    - zlib (Compression library)
    - minizip : Mini zip and unzip based on zlib
    - minizip-devel : Development files for zlib-minizip
description:
    - The zlib library is a compression library that aims to be unobtrusive.
    - minizip : Mini zip and unzip based on zlib
    - minizip-devel : Mini zip and unzip based on zlib
devel      : yes
emul32     : yes
patterns   :
    - minizip :
        - /usr/lib64/libminizip.so.*
    - minizip-devel :
        - /usr/include/minizip/*
        - /usr/lib64/libminizip.a
        - /usr/lib64/libminizip.so
        - /usr/lib64/pkgconfig/minizip.pc
setup      : |
    %patch -p1 < $pkgfiles/no_ldconfig.patch
    ./configure --prefix=/usr --libdir=%libdir%

    # configure minizip
    pushd contrib/minizip
    if [[ -z "${EMUL32BUILD}" ]]; then
        %reconfigure
    fi
    popd
build      : |
    %make

    # build minizip
    pushd contrib/minizip
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make
    fi
    popd
install    : |
    %make_install

    # install minizip
    pushd contrib/minizip
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make_install
    fi
    popd
