name       : zlib
version    : 1.2.11
release    : 13
source     :
    - http://zlib.net/zlib-1.2.11.tar.gz : c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
homepage   : http://www.zlib.net
license    : ZLIB
component  : system.base
summary    : zlib (Compression library)
description: |
    The zlib library is a compression library that aims to be unobtrusive.
devel      : yes
emul32     : yes
optimize   : speed
setup      : |
    %patch -p1 < $pkgfiles/no_ldconfig.patch
    ./configure --prefix=/usr \
                --libdir=%libdir%
build      : |
    %make
install    : |
    %make_install
